### PR TITLE
Joseph tarrazi/issue120

### PR DESCRIPTION
**Pull request by JosephTarrazi**
Fixes category links #120
Fixes Items page > category routing #121
Fixes Category component props #122
Fixes ItemsList props #123
Implemented sorting

### CODE REVIEW

**Comment by adlogi** [comment]
Thanks @JosephTarrazi. There are many conflicts which I couldn't resolve. Please resolve them. In the future, please have separate pull requests for separate issues.

**Comment by JosephTarrazi** [comment]
@adlogi thank you I will have separate pull requests for separate issues in the future. I tried to solve the conflicts but I saw some things that might be related to firebase which I know nothing about and I don't know if some of them are just there to test or are actual work.

**Comment by adlogi** [comment]
@JosephTarrazi please coordinate this with @Skia69.

**Comment by Skia69** [comment]
` const [query, setQuery] = useState('');` has been removed and all the filters related to the items page have been moved up the tree and put inside the itemsPage

**Pull request closed without merging**
